services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./backend:/workspace/backend
    container_name: backend-container

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./frontend:/workspace/frontend
    container_name: frontend-container

networks:
  app-network:
    driver: bridge
